package com.trioPlus.supportCenter.form;

// default package
// Generated Jan 10, 2015 1:07:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * SystemNotificationAffectedList generated by hbm2java
 */
public class SystemNotificationAffectedList implements java.io.Serializable {

	private SystemNotificationAffectedListId id;

	public SystemNotificationAffectedList() {
	}

	public SystemNotificationAffectedList(SystemNotificationAffectedListId id) {
		this.id = id;
	}

	public SystemNotificationAffectedListId getId() {
		return this.id;
	}

	public void setId(SystemNotificationAffectedListId id) {
		this.id = id;
	}

}
