package com.trioPlus.supportCenter.entity;

// default package
// Generated Jan 10, 2015 1:07:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * SystemNotificationAffectedListId generated by hbm2java
 */
public class SystemNotificationAffectedListId implements java.io.Serializable {

	private int notificationId;
	private int emailId;

	public SystemNotificationAffectedListId() {
	}

	public SystemNotificationAffectedListId(int notificationId, int emailId) {
		this.notificationId = notificationId;
		this.emailId = emailId;
	}

	public int getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	public int getEmailId() {
		return this.emailId;
	}

	public void setEmailId(int emailId) {
		this.emailId = emailId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SystemNotificationAffectedListId))
			return false;
		SystemNotificationAffectedListId castOther = (SystemNotificationAffectedListId) other;

		return (this.getNotificationId() == castOther.getNotificationId())
				&& (this.getEmailId() == castOther.getEmailId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNotificationId();
		result = 37 * result + this.getEmailId();
		return result;
	}

}
