package com.trioPlus.supportCenter.entity;

// default package
// Generated Jan 10, 2015 1:07:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SystemNotification generated by hbm2java
 */
public class SystemNotification implements java.io.Serializable {

	private int notificationId;
	private String notificationName;
	private String notificationType;
	private Date notificationDuration;
	private String notificationAction;

	public SystemNotification() {
	}

	public SystemNotification(int notificationId, String notificationName) {
		this.notificationId = notificationId;
		this.notificationName = notificationName;
	}

	public SystemNotification(int notificationId, String notificationName,
			String notificationType, Date notificationDuration,
			String notificationAction) {
		this.notificationId = notificationId;
		this.notificationName = notificationName;
		this.notificationType = notificationType;
		this.notificationDuration = notificationDuration;
		this.notificationAction = notificationAction;
	}

	public int getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	public String getNotificationName() {
		return this.notificationName;
	}

	public void setNotificationName(String notificationName) {
		this.notificationName = notificationName;
	}

	public String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(String notificationType) {
		this.notificationType = notificationType;
	}

	public Date getNotificationDuration() {
		return this.notificationDuration;
	}

	public void setNotificationDuration(Date notificationDuration) {
		this.notificationDuration = notificationDuration;
	}

	public String getNotificationAction() {
		return this.notificationAction;
	}

	public void setNotificationAction(String notificationAction) {
		this.notificationAction = notificationAction;
	}

}
